name       : black-hole-solver
version    : 1.10.1
release    : 1
source     :
    - https://fc-solve.shlomifish.org/downloads/fc-solve/black-hole-solver-1.10.1.tar.xz : 36e1953a99e02e82489a3cb109fb590bcab307b4ddaec34cb0e67347668511e2
homepage   : https://www.shlomifish.org/open-source/projects/black-hole-solitaire-solver/
license    : MIT
component  : programming
summary    : Solvers and statistics for 'Golf' solitaire, 'Black Hole' solitaire, 'All in a Row' solitaire and related card patience games.
description: |
    Solvers and statistics for 'Golf' solitaire, 'Black Hole' solitaire, 'All in a Row' solitaire and related card patience games.
builddeps  :
    - perl-path-tiny
    - rinutils
setup      : |
    %cmake -DBUILD_STATIC_LIBRARY=OFF
build      : |
    %make
install    : |
    %make_install
